if(EXISTS "/home/semakiller/Рабочий стол/Projects/BMSTU/MazeProject1/project_on_raw_c/src/hello_doter[1]_tests.cmake")
  include("/home/semakiller/Рабочий стол/Projects/BMSTU/MazeProject1/project_on_raw_c/src/hello_doter[1]_tests.cmake")
else()
  add_test(hello_doter_NOT_BUILT hello_doter_NOT_BUILT)
endif()
